[package]
name = "RustRabbitMQ"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "RustRabbitMQ"
path = "src/main.rs"

[dependencies]
lapin = "2.5.1"
tokio = { version = "1.44.0", features = ["full"] } # Corrected
tokio-amqp = "2.0.0"
tokio-executor = "0.1.10"
serde = { version = "1.0.197", features = ["derive"] } # Corrected
serde_json = "1.0.140" # Corrected
futures-lite = "2.6.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19" # Corrected
tracing-bunyan-formatter = "0.3.10" # Corrected
async-trait = "0.1.87" # Corrected
futures = "0.3.31"
envy = "0.4.2" # Corrected
anyhow = "1.0.97"
futures-util = "0.3.31"
dotenv = "0.15.0"
thiserror = "2.0.12"