[package]
name = "RustRabbitMQ"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.3" # Or the latest version
tokio = { version = "1", features = ["full"] } 
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"
futures-lite = "1.12"  # Add this line